name: response
description: Flutter application for disaster management.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  introduction_screen: ^1.0.8
  drop_cap_text: ^1.0.7
  validators: ^2.0.0

  url_launcher: ^5.5.0
  share: '>=0.6.4+3 <2.0.0'
  flutter_screenutil: ^2.3.1
  intl:

  google_maps_flutter: ^0.5.28+1
  flutter_google_places: ^0.2.6
  geolocator: ^5.3.2+2
  geocoder: ^0.2.1

#  flutter_sms: ^2.0.1+2
#  simple_animations: ^1.0.0

#  modal_progress_hud: ^0.1.3
#  giffy_dialog: ^1.7.0
#  email_validator: ^1.0.0
#  pin_code_fields: ^4.0.0

  provider: ^4.3.1
  flutter_dialogflow: ^0.1.2
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.7
  firebase_auth: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/json/credentials.json
#    - language/en.json
#    - language/hi.json
#    - language/mr.json

  fonts:
    - family: BungeeShade
      fonts:
        - asset: assets/fonts/BungeeShade-Regular.ttf

    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf

    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Regular.ttf

    - family: FredokaOne
      fonts:
        - asset: assets/fonts/FredokaOne.ttf

    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-Regular.ttf

    - family: Anton-Regular
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf

    - family: PlayfairDisplay-Bold
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf

    - family: PlayfairDisplay-Regular
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf

#    Custom Icons
    - family: Maps
      fonts:
        - asset: assets/fonts/Maps.ttf

    - family: News
      fonts:
        - asset: assets/fonts/News.ttf

    - family: Idea
      fonts:
        - asset: assets/fonts/Idea.ttf

    - family: Share
      fonts:
        - asset: assets/fonts/Share.ttf

    - family: ArrowFront
      fonts:
        - asset: assets/fonts/ArrowFront.ttf

    - family: HeartIcon
      fonts:
        - asset: assets/fonts/HeartIcon.ttf

    - family: Emergency
      fonts:
        - asset: assets/fonts/Emergency.ttf

    - family: DrawerIcon
      fonts:
        - asset: assets/fonts/DrawerIcon.ttf


